# Generated by Django 6.0.6 on 2026-06-29 23:39
# O carimbo do Django mostrando a versão exata do framework e o momento em que este manual foi gerado acima.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Indica que esta é a PRIMEIRA migração do seu app. Ela vai criar a base de tudo do zero.
    initial = True

    # AS DEPENDÊNCIAS:
    # O Django é inteligente. Ele sabe que, para criar a tabela de 'Post', o banco de dados precisa 
    # ter criado ANTES a tabela de Usuários (User), afinal, o Post aponta para um Autor.
    # Essa linha garante que o Django só rode esse arquivo DEPOIS que a tabela de usuários padrão do sistema estiver pronta.
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # AS OPERAÇÕES (O que o banco vai fazer de fato):
    operations = [
        # Comando para criar uma nova tabela/modelo chamada 'Post'
        migrations.CreateModel(
            name='Post',
            
            # Aqui estão listadas todas as colunas que essa tabela terá no banco de dados:
            fields=[
                # O CAMPO INVISÍVEL:
                # Reparou que você NÃO escreveu o campo 'id' no seu arquivo models.py? 
                # O Django coloca ele automaticamente aqui! Ele cria uma chave primária (primary_key) 
                # que se autoincrementa (1, 2, 3...) para identificar unicamente cada post do seu site.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                # Abaixo, ele simplesmente mapeou e copiou as regras exatas de tamanho e unicidade que você definiu:
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                
                # Note que ele já trouxe as opções de escolhas do STATUS (Draft e Publish) resolvidas:
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                
                # E o relacionamento finalizado, convertendo o 'User' para a configuração interna 'settings.AUTH_USER_MODEL':
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]